"""
Claw-DAW Integration Adapter for Maestro CLI
Allows exporting Maestro Pydantic model configurations (Tracks & Sections)
into deterministic, offline, headless claw-daw scripts.
"""

import logging
from pathlib import Path
from typing import Dict, Any, List, Optional
import shutil
import subprocess

from maestro_cli.models import Tracks, Sections, Song
from maestro_cli.config import settings

logger = logging.getLogger(__name__)


class ClawDawAdapter:
    """
    Adapter to bridge Maestro CLI objects and claw-daw CLI executions.
    Provides:
    1. Translation of Maestro tracks/sections into claw-daw script files (.txt).
    2. Headless execution of claw-daw to export WAV, MP3, MIDI, and JSON report files.
    """

    def __init__(self, bin_path: Optional[str] = None):
        self.bin_path = bin_path or shutil.which("claw-daw") or "claw-daw"
        logger.info("Initialized ClawDawAdapter using binary: %s", self.bin_path)

    def is_claw_daw_available(self) -> bool:
        """Checks if claw-daw executable is available on PATH."""
        return shutil.which("claw-daw") is not None

    def translate_to_script(
        self,
        song: Song,
        sections: Sections,
        tracks: Tracks,
        project_dir: Path,
        output_prefix: str
    ) -> Path:
        """
        Translates Maestro models into a claw-daw instruction script.
        Writes the result to project_dir/tools/<output_prefix>.txt.
        """
        script_dir = project_dir / "tools"
        script_dir.mkdir(parents=True, exist_ok=True)
        script_file = script_dir / f"{output_prefix}.txt"

        lines = [
            f"# claw-daw script generated by Maestro CLI",
            f"new_project {output_prefix} {song.tempo_bpm}",
            f"set_swing {int(song.constraints.swing * 100)}",
            ""
        ]

        # Define and configure tracks
        has_lead = False
        for idx, track in enumerate(tracks.tracks):
            track_name = track.name.replace(" ", "_")
            role = track.role

            # Map Maestro roles to claw-daw kits/programs
            if role == "drums":
                lines.append(f"add_track {track_name} 0")
                # Choose appropriate drum kit
                kit_name = "trap_hard" if "afrobeats" in song.style else "gm_basic"
                lines.append(f"set_kit {idx} {kit_name}")
            elif role == "bass":
                lines.append(f"add_track {track_name} 0")
                lines.append(f"set_808 {idx} clean")
            else:
                # Map role to MIDI Program number
                prog = 0  # Default piano
                if role == "keys":
                    prog = 4  # Rhodes/E.Piano
                elif role == "pad":
                    prog = 89  # Warm Pad
                elif role in ["lead", "melody", "strings"]:
                    prog = 40  # Violin / Solo strings
                    has_lead = True
                lines.append(f"add_track {track_name} {prog}")
                lines.append(f"set_volume {idx} {int(track.volume * 127)}")
                lines.append(f"set_pan {idx} {int(track.pan * 127)}")

        # Dynamically read and parse MIDI files for each track
        total_bars = sum(section.bars for section in sections.sections) if sections and sections.sections else 64
        
        for idx, track in enumerate(tracks.tracks):
            track_name = track.name.replace(" ", "_")
            role = track.role
            midi_path = project_dir / track.midi_file
            
            pat_name = f"pat_{role}_full"
            lines.append(f"new_pattern {idx} {pat_name} {total_bars}:0")
            
            if midi_path.exists():
                try:
                    import mido
                    mid = mido.MidiFile(str(midi_path))
                    ticks_per_beat = mid.ticks_per_beat
                    ticks_per_bar = ticks_per_beat * 4
                    
                    active_notes = {}
                    
                    for mido_track in mid.tracks:
                        current_tick = 0
                        for msg in mido_track:
                            current_tick += msg.time
                            if msg.type == 'note_on' and msg.velocity > 0:
                                active_notes[msg.note] = (current_tick, msg.velocity)
                            elif msg.type == 'note_off' or (msg.type == 'note_on' and msg.velocity == 0):
                                if msg.note in active_notes:
                                    start_tick, velocity = active_notes.pop(msg.note)
                                    duration_ticks = current_tick - start_tick
                                    
                                    # Normalize ticks to claw-daw 480 ticks/beat standard if different
                                    if ticks_per_beat != 480:
                                        scale = 480.0 / ticks_per_beat
                                        start_tick = int(start_tick * scale)
                                        duration_ticks = int(duration_ticks * scale)
                                        current_ticks_per_beat = 480
                                        current_ticks_per_bar = 1920
                                    else:
                                        current_ticks_per_beat = ticks_per_beat
                                        current_ticks_per_bar = ticks_per_bar
                                    
                                    bar = start_tick // current_ticks_per_bar
                                    rem = start_tick % current_ticks_per_bar
                                    beat = rem // current_ticks_per_beat
                                    tick = rem % current_ticks_per_beat
                                    
                                    dur_bar = duration_ticks // current_ticks_per_bar
                                    rem_dur = duration_ticks % current_ticks_per_bar
                                    dur_beat = rem_dur // current_ticks_per_beat
                                    dur_tick = rem_dur % current_ticks_per_beat
                                    
                                    pitch_val = msg.note
                                    if role == "drums":
                                        if pitch_val in [35, 36]:
                                            pitch_str = "kick"
                                        elif pitch_val in [38, 40]:
                                            pitch_str = "snare"
                                        elif pitch_val in [42, 44]:
                                            pitch_str = "hihat"
                                        elif pitch_val in [46]:
                                            pitch_str = "openhat"
                                        elif pitch_val in [41, 43]:
                                            pitch_str = "tom_low"
                                        elif pitch_val in [45, 47]:
                                            pitch_str = "tom_mid"
                                        elif pitch_val in [48, 50]:
                                            pitch_str = "tom_high"
                                        elif pitch_val in [49, 57]:
                                            pitch_str = "crash"
                                        elif pitch_val in [51]:
                                            pitch_str = "ride"
                                        else:
                                            pitch_str = str(pitch_val)
                                    else:
                                        pitch_str = str(pitch_val)
                                        
                                    lines.append(f"add_note_pat {idx} {pat_name} {pitch_str} {bar}:{beat}:{tick} {dur_bar}:{dur_beat}:{dur_tick} {velocity}")
                except Exception as e:
                    logger.error("Failed to parse MIDI file %s: %s", midi_path, e)
            else:
                logger.warning("MIDI file %s does not exist", midi_path)
                
            lines.append(f"place_pattern {idx} {pat_name} 0:0")
            lines.append("")

        # Save and Export files
        lines.append("# Outputs & Deliverables")
        lines.append(f"export_project out/{output_prefix}.json")
        lines.append(f"export_midi out/{output_prefix}.mid")
        lines.append(f"export_mp3 out/{output_prefix}.mp3 preset=clean")

        script_file.write_text("\n".join(lines))
        logger.info("Wrote claw-daw script: %s", script_file)
        return script_file

    def execute_render(
        self,
        script_path: Path,
        soundfont_path: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Executes claw-daw in headless mode to render the project.
        """
        if not self.is_claw_daw_available():
            return {
                "success": False,
                "error": "claw-daw not found on system PATH."
            }

        # Resolve SoundFont
        sf2 = soundfont_path
        if not sf2:
            # Check default SoundFont paths
            for sf2_path in [
                "/usr/share/sounds/sf2/default-GM.sf2",
                "/usr/share/sounds/sf2/FluidR3_GM.sf2",
                "/usr/share/sounds/sf2/GeneralUser_GS.sf2"
            ]:
                if Path(sf2_path).exists():
                    sf2 = sf2_path
                    break

        cmd = [
            self.bin_path,
            "--headless",
            "--script", str(script_path)
        ]
        if sf2:
            cmd.extend(["--soundfont", sf2])

        logger.info("Executing claw-daw: %s", " ".join(cmd))
        try:
            res = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
            if res.returncode == 0:
                return {
                    "success": True,
                    "stdout": res.stdout,
                    "stderr": res.stderr,
                    "method": "claw-daw"
                }
            else:
                return {
                    "success": False,
                    "error": res.stderr or res.stdout or "Command failed"
                }
        except subprocess.TimeoutExpired:
            return {
                "success": False,
                "error": "claw-daw rendering timed out."
            }
        except Exception as e:
            return {
                "success": False,
                "error": str(e)
            }
