"""
Structured Outputs Module for Maestro CLI

Handles validation, parsing, and repair of LLM-generated structured outputs.
Ensures all AI responses conform to expected schemas before processing.

This module is the foundation for Phase 3: making the system robust and intelligent.
"""

import json
import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Type, TypeVar, Union

from pydantic import BaseModel, Field, ValidationError

logger = logging.getLogger(__name__)


# ============================================================================
# BASE TYPES
# ============================================================================

class OutputStatus(str, Enum):
    """Status of a structured output"""
    VALID = "valid"
    INVALID = "invalid"
    PARTIAL = "partial"
    REPAIRED = "repaired"


class OutputType(str, Enum):
    """Types of structured outputs"""
    COMPOSE = "compose"
    ARRANGE = "arrange"
    ORCHESTRATE = "orchestrate"
    CRITIQUE = "critique"
    REPAIR = "repair"
    ANALYZE = "analyze"


# ============================================================================
# SCHEMAS FOR EACH OUTPUT TYPE
# ============================================================================

class ComposeOutput(BaseModel):
    """
    Structured output for the compose step.
    Generated by LLM to create the musical foundation.
    """
    output_type: OutputType = OutputType.COMPOSE
    project_id: str = Field(..., description="Unique project identifier")
    song_title: str = Field(..., description="Title of the composition")
    style: str = Field(..., description="Musical style (e.g., gospel, jazz, classical)")
    bpm: int = Field(ge=40, le=200, description="Tempo in BPM")
    time_signature: str = Field(default="4/4", description="Time signature")
    key: str = Field(default="C", description="Musical key")
    sections: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="List of song sections with their properties"
    )
    chords_progression: List[str] = Field(
        default_factory=list,
        description="Chord progression for the song"
    )
    mood: str = Field(default="", description="Emotional mood of the piece")
    
    # Metadata
    model_used: str = Field(default="", description="LLM model used for generation")
    tokens_used: int = Field(default=0, description="Number of tokens consumed")
    generated_at: str = Field(default="", description="ISO timestamp of generation")
    
    class Config:
        json_schema_extra = {
            "example": {
                "output_type": "compose",
                "project_id": "my_song_001",
                "song_title": "Gospel Morning",
                "style": "gospel",
                "bpm": 72,
                "time_signature": "4/4",
                "key": "C",
                "sections": [
                    {"name": "intro", "bars": 4, "density": "sparse"},
                    {"name": "verse", "bars": 8, "density": "moderate"},
                    {"name": "chorus", "bars": 8, "density": "high"}
                ],
                "chords_progression": ["C", "G", "Am", "F"],
                "mood": "inspiring"
            }
        }


class ArrangeOutput(BaseModel):
    """
    Structured output for the arrange step.
    Transforms composition into track-level arrangements.
    """
    output_type: OutputType = OutputType.ARRANGE
    project_id: str = Field(..., description="Unique project identifier")
    tracks: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="List of track configurations"
    )
    arrangements: Dict[str, Any] = Field(
        default_factory=dict,
        description="Detailed arrangement instructions per section"
    )
    layering_strategy: str = Field(
        default="balanced",
        description="Strategy for layering instruments"
    )
    
    # Metadata
    model_used: str = Field(default="", description="LLM model used")
    tokens_used: int = Field(default=0, description="Tokens consumed")
    generated_at: str = Field(default="", description="ISO timestamp")
    
    class Config:
        json_schema_extra = {
            "example": {
                "output_type": "arrange",
                "project_id": "my_song_001",
                "tracks": [
                    {
                        "name": "keys_main",
                        "role": "keys",
                        "register": "mid",
                        "density": "moderate",
                        "pattern": "arpeggiated"
                    },
                    {
                        "name": "bass_main",
                        "role": "bass",
                        "register": "low",
                        "density": "sparse",
                        "pattern": "root_fifth"
                    }
                ],
                "arrangements": {
                    "intro": {"keys_main": {"volume": 0.6, "effects": ["reverb"]}},
                    "chorus": {"keys_main": {"volume": 0.8, "effects": ["reverb", "delay"]}}
                }
            }
        }


class OrchestrateOutput(BaseModel):
    """
    Structured output for the orchestrate step.
    Assigns specific instruments/plugins to tracks.
    """
    output_type: OutputType = OutputType.ORCHESTRATE
    project_id: str = Field(..., description="Unique project identifier")
    track_instruments: Dict[str, Dict[str, Any]] = Field(
        default_factory=dict,
        description="Instrument assignment per track"
    )
    plugin_mappings: Dict[str, str] = Field(
        default_factory=dict,
        description="Mapping of track roles to plugin IDs"
    )
    expression_map: Dict[str, Dict[str, Any]] = Field(
        default_factory=dict,
        description="Expression settings (volume, pan, etc.) per track"
    )
    
    # Metadata
    model_used: str = Field(default="", description="LLM model used")
    tokens_used: int = Field(default=0, description="Tokens consumed")
    generated_at: str = Field(default="", description="ISO timestamp")
    
    class Config:
        json_schema_extra = {
            "example": {
                "output_type": "orchestrate",
                "project_id": "my_song_001",
                "track_instruments": {
                    "keys_main": {
                        "plugin": "EPiano_VST3",
                        "preset": "Warm Suitcase",
                        "midi_channel": 0
                    },
                    "bass_main": {
                        "plugin": "BassSynth_VST3",
                        "preset": "Round Finger",
                        "midi_channel": 1
                    }
                },
                "expression_map": {
                    "keys_main": {"volume": 0.8, "pan": 0.2},
                    "bass_main": {"volume": 0.7, "pan": -0.2}
                }
            }
        }


# ============================================================================
# REPAIR OUTPUT (for fix actions)
# ============================================================================

class RepairOutput(BaseModel):
    """
    Structured output for the repair step.
    Contains fixes for issues detected during critique.
    """
    output_type: OutputType = OutputType.REPAIR
    project_id: str = Field(..., description="Unique project identifier")
    original_issues: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="List of issues that triggered the repair"
    )
    repairs_applied: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="List of repairs that were applied"
    )
    tracks_modified: List[str] = Field(
        default_factory=list,
        description="List of track names that were modified"
    )
    success: bool = Field(default=True, description="Were all repairs successful?")
    
    # Metadata
    model_used: str = Field(default="", description="LLM model used")
    tokens_used: int = Field(default=0, description="Tokens consumed")
    generated_at: str = Field(default="", description="ISO timestamp")
    
    class Config:
        json_schema_extra = {
            "example": {
                "output_type": "repair",
                "project_id": "my_song_001",
                "original_issues": [
                    {"type": "register_collision", "tracks": ["keys_main", "lead_main"]}
                ],
                "repairs_applied": [
                    {
                        "action": "raise_lead_register",
                        "target": "lead_main",
                        "params": {"octave_shift": +1}
                    }
                ],
                "tracks_modified": ["lead_main"],
                "success": True
            }
        }


# ============================================================================
# ANALYSIS OUTPUT (for understanding existing songs)
# ============================================================================

class AnalyzeOutput(BaseModel):
    """
    Structured output for analyzing existing MIDI/audio files.
    """
    output_type: OutputType = OutputType.ANALYZE
    project_id: str = Field(..., description="Unique project identifier")
    bpm: Optional[float] = Field(default=None, description="Detected BPM")
    key: Optional[str] = Field(default=None, description="Detected key")
    time_signature: Optional[str] = Field(default=None, description="Detected time signature")
    duration_seconds: float = Field(default=0.0, description="Total duration in seconds")
    sections: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Detected sections with timing"
    )
    instruments: List[str] = Field(
        default_factory=list,
        description="Detected instruments/timbre categories"
    )
    complexity_score: float = Field(
        ge=0.0, le=1.0,
        default=0.5,
        description="Complexity score (0-1)"
    )
    density_score: float = Field(
        ge=0.0, le=1.0,
        default=0.5,
        description="Density score (0-1)"
    )
    
    # Metadata
    model_used: str = Field(default="", description="LLM model used")
    tokens_used: int = Field(default=0, description="Tokens consumed")
    generated_at: str = Field(default="", description="ISO timestamp")


# ============================================================================
# VALIDATION & PARSING
# ============================================================================

T = TypeVar('T', bound=BaseModel)


@dataclass
class ValidationResult:
    """Result of validating a structured output"""
    status: OutputStatus
    output: Optional[BaseModel] = None
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    raw_input: Optional[str] = None
    repaired: bool = False
    
    def is_valid(self) -> bool:
        """Check if validation passed"""
        return self.status == OutputStatus.VALID or self.status == OutputStatus.REPAIRED


class StructuredOutputValidator:
    """
    Validates and parses LLM responses into structured outputs.
    Handles repair prompts when validation fails.
    """
    
    # Map output_type to Pydantic model class
    OUTPUT_MODELS: Dict[OutputType, Type[BaseModel]] = {
        OutputType.COMPOSE: ComposeOutput,
        OutputType.ARRANGE: ArrangeOutput,
        OutputType.ORCHESTRATE: OrchestrateOutput,
        OutputType.CRITIQUE: "Critique",  # Imported from models.critique
        OutputType.REPAIR: RepairOutput,
        OutputType.ANALYZE: AnalyzeOutput,
    }
    
    def __init__(
        self,
        repair_prompt_generator: Optional[Callable[[str, OutputType, List[str]], str]] = None,
        max_repair_attempts: int = 3
    ):
        self.repair_prompt_generator = repair_prompt_generator
        self.max_repair_attempts = max_repair_attempts
        
    def validate(
        self,
        raw_output: Union[str, Dict[str, Any]],
        output_type: OutputType
    ) -> ValidationResult:
        """
        Validate a raw LLM output against the expected schema.
        
        Args:
            raw_output: Raw output from LLM (JSON string or dict)
            output_type: Type of output expected
            
        Returns:
            ValidationResult with status and parsed output
        """
        # Parse string to dict if needed
        if isinstance(raw_output, str):
            raw_dict = self._safe_parse_json(raw_output)
        else:
            raw_dict = raw_output
            
        # Add output_type if missing
        if raw_dict and "output_type" not in raw_dict:
            raw_dict["output_type"] = output_type.value
        
        model_class = self.OUTPUT_MODELS.get(output_type)
        if model_class is None:
            return ValidationResult(
                status=OutputStatus.INVALID,
                errors=[f"Unknown output type: {output_type}"]
            )
        
        # Handle Critique special case (imported from models)
        if output_type == OutputType.CRITIQUE:
            from maestro_cli.models.critique import Critique
            model_class = Critique
        
        # Try to parse and validate
        try:
            output = model_class(**raw_dict)
            return ValidationResult(
                status=OutputStatus.VALID,
                output=output,
                raw_input=raw_output if isinstance(raw_output, str) else json.dumps(raw_output)
            )
        except ValidationError as e:
            errors = [f"{err['loc']}: {err['msg']}" for err in e.errors()]
            logger.warning(f"Validation failed for {output_type}: {errors}")
            
            # Attempt repair if possible
            if self.repair_prompt_generator and self.max_repair_attempts > 0:
                repaired_result = self._attempt_repair(
                    raw_output, output_type, errors, model_class
                )
                if repaired_result.is_valid():
                    return repaired_result
                return ValidationResult(
                    status=OutputStatus.INVALID,
                    errors=repaired_result.errors,
                    raw_input=raw_output if isinstance(raw_output, str) else json.dumps(raw_output)
                )
            
            return ValidationResult(
                status=OutputStatus.INVALID,
                errors=errors,
                raw_input=raw_output if isinstance(raw_output, str) else json.dumps(raw_output)
            )
        except Exception as e:
            logger.error(f"Unexpected error validating {output_type}: {e}")
            return ValidationResult(
                status=OutputStatus.INVALID,
                errors=[f"Unexpected error: {str(e)}"],
                raw_input=raw_output if isinstance(raw_output, str) else json.dumps(raw_output)
            )
    
    def validate_json_string(
        self,
        json_string: str,
        output_type: OutputType
    ) -> ValidationResult:
        """Validate a JSON string output"""
        return self.validate(json_string, output_type)
    
    def validate_dict(
        self,
        data: Dict[str, Any],
        output_type: OutputType
    ) -> ValidationResult:
        """Validate a dictionary output"""
        return self.validate(data, output_type)
    
    def _safe_parse_json(self, json_string: str) -> Dict[str, Any]:
        """Safely parse JSON, returning empty dict on failure"""
        try:
            return json.loads(json_string)
        except json.JSONDecodeError as e:
            logger.warning(f"Invalid JSON: {e}")
            return {}
    
    def _attempt_repair(
        self,
        raw_output: Union[str, Dict[str, Any]],
        output_type: OutputType,
        errors: List[str],
        model_class: Type[BaseModel]
    ) -> ValidationResult:
        """Attempt to repair a failed validation"""
        # Try to import call_llm if available, otherwise skip repair
        try:
            from maestro_cli.llm import call_llm
            llm_available = True
        except (ImportError, ModuleNotFoundError):
            llm_available = False
        
        for attempt in range(self.max_repair_attempts):
            repair_prompt = self.repair_prompt_generator(
                raw_output if isinstance(raw_output, str) else json.dumps(raw_output),
                output_type,
                errors
            )
            
            logger.info(f"Repair attempt {attempt + 1}/{self.max_repair_attempts} for {output_type}")
            
            try:
                # Call LLM for repair if available
                if llm_available:
                    repaired_json = call_llm(repair_prompt)
                else:
                    # No LLM available, cannot repair
                    logger.warning("LLM module not available, skipping repair")
                    break
                
                repaired_dict = self._safe_parse_json(repaired_json)
                
                output = model_class(**repaired_dict)
                return ValidationResult(
                    status=OutputStatus.REPAIRED,
                    output=output,
                    raw_input=raw_output if isinstance(raw_output, str) else json.dumps(raw_output),
                    repaired=True
                )
            except (ValidationError, Exception) as e:
                logger.debug(f"Repair attempt {attempt + 1} failed: {e}")
                if attempt == self.max_repair_attempts - 1:
                    break
                continue
        
        return ValidationResult(
            status=OutputStatus.INVALID,
            errors=[f"Failed to repair after {self.max_repair_attempts} attempts"] + errors,
            raw_input=raw_output if isinstance(raw_output, str) else json.dumps(raw_output)
        )


# ============================================================================
# DEFAULT VALIDATOR INSTANCE
# ============================================================================

def default_repair_prompt(
    raw_output: str,
    output_type: OutputType,
    errors: List[str]
) -> str:
    """Generate a repair prompt for the LLM"""
    error_list = "\n".join([f"- {e}" for e in errors])
    
    return f"""
You previously generated the following output for a {output_type.value} task:
{raw_output}

However, validation found the following issues:
{error_list}

Please fix these issues and return a corrected JSON output that strictly follows the schema.
Return ONLY the corrected JSON, no explanations or apologies.
"""


# Global validator instance
validator = StructuredOutputValidator(
    repair_prompt_generator=default_repair_prompt,
    max_repair_attempts=2
)


# ============================================================================
# CONVENIENCE FUNCTIONS
# ============================================================================

def validate_compose_output(raw_output: Union[str, Dict[str, Any]]) -> ValidationResult:
    """Validate a compose output"""
    return validator.validate(raw_output, OutputType.COMPOSE)


def validate_arrange_output(raw_output: Union[str, Dict[str, Any]]) -> ValidationResult:
    """Validate an arrange output"""
    return validator.validate(raw_output, OutputType.ARRANGE)


def validate_orchestrate_output(raw_output: Union[str, Dict[str, Any]]) -> ValidationResult:
    """Validate an orchestrate output"""
    return validator.validate(raw_output, OutputType.ORCHESTRATE)


def validate_repair_output(raw_output: Union[str, Dict[str, Any]]) -> ValidationResult:
    """Validate a repair output"""
    return validator.validate(raw_output, OutputType.REPAIR)


def validate_analyze_output(raw_output: Union[str, Dict[str, Any]]) -> ValidationResult:
    """Validate an analyze output"""
    return validator.validate(raw_output, OutputType.ANALYZE)


def validate_critique_output(raw_output: Union[str, Dict[str, Any]]) -> ValidationResult:
    """Validate a critique output"""
    return validator.validate(raw_output, OutputType.CRITIQUE)
